### ISSUE TITLE
some emojis not showing

### ISSUE THREAD

**Issue by ReggieMiller1** [Alfaizkhan/flutter-emoji-selector#1]
what causes some emojis not to get displayed but show the square with a cross. i thought all emojis were supposed to be displayed just like in WhatsApp

**Comment by Alfaizkhan** [comment]
@ReggieMiller1 
Can you please share the logs when you open the emoji sheet.
Is there any exceptions?

**Comment by ReggieMiller1** [comment]
> @ReggieMiller1 Can you please share the logs when you open the emoji sheet. Is there any exceptions?
![Screenshot_20220717-133305](https://user-images.githubusercontent.com/52163493/179396236-2f1d2017-0fb5-43c9-9f20-b0789a7e57fc.png)

look at the screenshot...those blue squares

**Comment by Alfaizkhan** [comment]
@ReggieMiller1 
Device or Emulator Name?

**Comment by ReggieMiller1** [comment]
> @ReggieMiller1 Device or Emulator Name?

its a real device...Samsung Galaxy Grand Prime... my question is: is it supposed to showing those squares?

**Comment by Alfaizkhan** [comment]
@ReggieMiller1 
Is is not supposed to show those squares.
I'm looking into it.

**Comment by Alfaizkhan** [comment]
@ReggieMiller1 
I have tried in many devices and emulator, but could not reproduced it.
I think, It's device specific issue. 
Samsung provides it's own set of emojis, which is different from the basic emojis.
